import type { Metadata } from 'next';
import { inter, notoSansJP } from '@/lib/font';
import './globals.css';

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export const metadata: Metadata = {
  title: 'udemy-react-notion-clone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ja">
      <body className={`${inter.variable} ${notoSansJP.variable} antialiased font-sans`}>
        {children}
      </body>
    </html>
  );
}
