import type { Metadata } from 'next';
import { inter, notoSansJP } from '@/lib/font';
import './globals.css';
import '@/app/globals.css';
import Footer from '@/app/_components/Footer';
import Header from '@/app/_components/Header';

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export const metadata: Metadata = {
  title: 'udemy-react-notion-clone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ja">
      <body
        className={`${inter.variable} ${notoSansJP.variable} antialiased font-sans bg-background`}
      >
        <div className="flex flex-col h-screen">
          <header className="h-20 shrink-0">
            <Header />
          </header>
          <main className="flex-1">{children}</main>
          <footer className="h-20 shrink-0">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
